# Generated by Django 5.2.6 on 2025-09-22 21:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SettlementChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('advanced_loan_amount', models.DecimalField(decimal_places=2, help_text='Total debt amount that borrower signed for (J13)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('first_wired_amount', models.DecimalField(decimal_places=2, help_text='Initial money actually transferred to borrower (J14)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_settlement_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of all settlement charges (J22)', max_digits=12)),
                ('first_loan_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('initial_interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.13'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted'), ('pending', 'Pending')], default='active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_cards', to='loans.borrower')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(blank=True, null=True)),
                ('charge_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_payments', to='loans.loancard')),
            ],
            options={
                'ordering': ['charge_date'],
            },
        ),
        migrations.CreateModel(
            name='SettlementCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_charges', to='loans.loancard')),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.settlementchargetype')),
            ],
            options={
                'ordering': ['charge_type__display_order'],
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('draw_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('draw_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('inspection_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_draws', to='loans.loancard')),
            ],
            options={
                'ordering': ['draw_number'],
                'unique_together': {('loan_card', 'draw_number')},
            },
        ),
    ]
