# Generated by Django 5.2.6 on 2025-09-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(help_text='0 for daily, 1,2,3... for monthly periods')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
                ('charge_date', models.DateField()),
                ('calculated_amount', models.DecimalField(decimal_places=2, help_text='Auto-calculated interest amount', max_digits=12)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Manual adjustments to calculated amount', max_digits=12, null=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, help_text='QuickBooks Online invoice number', max_length=100, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_schedules', to='loans.loancard')),
            ],
            options={
                'ordering': ['loan_card', 'charge_date', 'period_number'],
                'unique_together': {('loan_card', 'period_type', 'period_number')},
            },
        ),
    ]
