# Generated by Django 5.2.6 on 2025-09-26 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_interestschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('extension_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('has_interest', models.BooleanField(default=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('loan_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='loans.loancard')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
