# Generated by Django 5.2.6 on 2025-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementcharge',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice or document number', max_length=100, null=True),
        ),
    ]
