# Generated by Django 5.2.6 on 2025-09-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_settlementcharge_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancard',
            name='advanced_loan_invoice',
            field=models.CharField(blank=True, help_text='Invoice or document number for main loan', max_length=100, null=True),
        ),
    ]
