# Generated by Django 5.2.6 on 2025-09-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loancard_advanced_loan_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Internal code (e.g., 'active')", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Active')", max_length=50)),
                ('color', models.CharField(default='#95a5a6', help_text='Hex color for UI', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Is this status available for selection')),
                ('order', models.IntegerField(default=0, help_text='Display order in dropdowns')),
                ('can_delete', models.BooleanField(default=True, help_text='Protect core statuses from deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Loan Statuses',
                'ordering': ['order', 'name'],
            },
        ),
    ]
