# Generated by Django 5.2.6 on 2025-09-27 22:11

from django.db import migrations


def seed_core_statuses(apps, schema_editor):
    LoanStatus = apps.get_model('loans', 'LoanStatus')
    core_statuses = [
        {
            'code': 'active',
            'name': 'Active',
            'color': '#27ae60',
            'order': 1,
            'can_delete': False,
        },
        {
            'code': 'closed',
            'name': 'Closed',
            'color': '#95a5a6',
            'order': 2,
            'can_delete': False,
        },
        {
            'code': 'defaulted',
            'name': 'Defaulted',
            'color': '#e74c3c',
            'order': 3,
            'can_delete': False,
        },
        {
            'code': 'pending',
            'name': 'Pending',
            'color': '#f39c12',
            'order': 4,
            'can_delete': False,
        },
    ]

    for status in core_statuses:
        LoanStatus.objects.update_or_create(
            code=status['code'],
            defaults={
                'name': status['name'],
                'color': status['color'],
                'order': status['order'],
                'can_delete': status['can_delete'],
                'is_active': True,
            }
        )


def unseed_core_statuses(apps, schema_editor):
    LoanStatus = apps.get_model('loans', 'LoanStatus')
    LoanStatus.objects.filter(code__in=['active', 'closed', 'defaulted', 'pending']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanstatus'),
    ]

    operations = [
        migrations.RunPython(seed_core_statuses, unseed_core_statuses),
    ]
