# Generated by Django 5.2.6 on 2025-09-27 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_seed_core_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancard',
            name='dynamic_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.loanstatus'),
        ),
    ]
