# Generated by Django 5.2.6 on 2025-09-27 22:15

from django.db import migrations


def sync_dynamic_status(apps, schema_editor):
    LoanCard = apps.get_model('loans', 'LoanCard')
    LoanStatus = apps.get_model('loans', 'LoanStatus')

    synced = 0
    missing = []

    for loan in LoanCard.objects.all():
        status_code = (loan.status or '').strip()
        if not status_code:
            continue

        try:
            status_obj = LoanStatus.objects.get(code=status_code)
        except LoanStatus.DoesNotExist:
            missing.append((loan.card_number, status_code))
            continue

        if loan.dynamic_status_id == status_obj.id:
            continue

        loan.dynamic_status = status_obj
        loan.save(update_fields=['dynamic_status'])
        synced += 1

    print(f"Synced dynamic status for {synced} loan(s).")
    if missing:
        print("No matching LoanStatus for the following loans:")
        for card_number, code in missing:
            print(f" - {card_number}: {code}")


def unsync_dynamic_status(apps, schema_editor):
    LoanCard = apps.get_model('loans', 'LoanCard')
    LoanCard.objects.update(dynamic_status=None)


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loancard_dynamic_status'),
    ]

    operations = [
        migrations.RunPython(sync_dynamic_status, unsync_dynamic_status),
    ]
