# Generated by Django 5.2.6 on 2025-09-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_sync_dynamic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanstatus',
            name='stops_interest_accrual',
            field=models.BooleanField(default=False, help_text='Stop calculating interest when loan has this status'),
        ),
    ]
