# Generated by Django 5.2.6 on 2025-09-30 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_loanstatus_stops_interest_accrual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('months_covered', models.IntegerField()),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_interest', to='loans.loancard')),
                ('settlement_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_interest_records', to='loans.settlementcharge')),
            ],
            options={
                'ordering': ['loan_card__card_number'],
            },
        ),
    ]
