# Generated by Django 5.2.6 on 2025-09-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_prepaidinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestschedule',
            name='payment_source',
            field=models.CharField(choices=[('bank', 'Bank Payment'), ('prepaid', 'Prepaid Balance')], default='bank', help_text='Where the interest payment came from', max_length=20),
        ),
    ]
